# -*- coding: utf-8 -*-
"""sickit image preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zw8rSe0yr0xeajQVBN_FC0rLR5-zYOKm
"""

from matplotlib import pyplot as plt

from skimage import io ## to read images

img1 = io.imread('/content/poultry2.jpg')
print(img1)
print(img1.size)
print(img1.shape)
print(type(img1))

plt.imshow(img1)

from skimage import transform as tf ## for transformation functions usage:

transform = tf.AffineTransform(scale=1, rotation = 0.9, translation=[50,100])

transformed_image = tf.warp(img1, transform)
plt.imshow(transformed_image)

